name: demo
description: Demo application for vyuh_node_flow package

version: 1.0.0+1
publish_to: none

resolution: workspace
environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  font_awesome_flutter: ^10.7.0
  go_router: ^17.0.0
  http: ^1.2.0
  mobx: ^2.5.0
  url_launcher: ^6.3.1
  vyuh_node_flow:
    path: ../vyuh_node_flow

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/node-flow-banner.png"
    background_color: "#ffffff"

flutter_native_splash:
  color: "#ffffff"
  image: assets/node-flow-banner.png
  web: true
  android: false
  ios: false
